Add firewall_rules column and users & database info in digitalocean_database. Closes #47
turbot/steampipe-plugin-digitalocean pull request #48
Opened 2022-04-13 05:52 UTC by karanpopat

# Example query results
<details>
  <summary>Results</summary>
  
```
> select title, jsonb_pretty(users) as users, jsonb_pretty(db_names) as db_names, jsonb_pretty(firewall_rules) as firewall_rules from digitalocean_database
+-----------------------+----------------------------+-------------------------+----------------------------------------------------------------+
| title                 | users                      | db_names                | firewall_rules                                                 |
+-----------------------+----------------------------+-------------------------+----------------------------------------------------------------+
| db-mongodb-blr1-45484 | [                          | [                       | [                                                              |
|                       |     {                      |     {                   |     {                                                          |
|                       |         "name": "doadmin", |         "name": "admin" |         "type": "droplet",                                     |
|                       |         "role": "primary"  |     },                  |         "uuid": "231c821b-1833-4516-9495-b79c520b2e5a",        |
|                       |     },                     |     {                   |         "value": "294979514",                                  |
|                       |     {                      |         "name": "karan" |         "created_at": "2022-04-12T09:56:55Z",                  |
|                       |         "name": "karan",   |     }                   |         "cluster_uuid": "05d8de22-f97d-44fb-8584-563aafff0225" |
|                       |         "role": "normal"   | ]                       |     },                                                         |
|                       |     }                      |                         |     {                                                          |
|                       | ]                          |                         |         "type": "ip_addr",                                     |
|                       |                            |                         |         "uuid": "744ce25e-047c-4d7f-944f-8dd08846e97b",        |
|                       |                            |                         |         "value": "203.171.244.10",                             |
|                       |                            |                         |         "created_at": "2022-04-12T09:56:55Z",                  |
|                       |                            |                         |         "cluster_uuid": "05d8de22-f97d-44fb-8584-563aafff0225" |
|                       |                            |                         |     },                                                         |
|                       |                            |                         |     {                                                          |
|                       |                            |                         |         "type": "app",                                         |
|                       |                            |                         |         "uuid": "efbba8f3-ad57-4b81-93e5-ec1c4f13a344",        |
|                       |                            |                         |         "value": "7783255e-f056-49a8-9e1b-8d559270ff67",       |
|                       |                            |                         |         "created_at": "2022-04-12T09:56:55Z",                  |
|                       |                            |                         |         "cluster_uuid": "05d8de22-f97d-44fb-8584-563aafff0225" |
|                       |                            |                         |     }                                                          |
|                       |                            |                         | ]                                                              |
+-----------------------+----------------------------+-------------------------+----------------------------------------------------------------+
```
</details>

2022-04-15 05:52 UTC, ParthaI commented on digitalocean/table_digitalocean_database.go
> +func getUsers(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getDatabaseUsers(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```
Also change the same in log statement.

2022-04-15 05:53 UTC, ParthaI commented on digitalocean/table_digitalocean_database.go
> +func getDbs(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getDatabaseNames(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```
Also change the same in log statement.

2022-04-15 05:53 UTC, ParthaI commented on digitalocean/table_digitalocean_database.go
> +func getFirewallRules(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```suggestion
func getDatabseFirewallRules(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
```
Also change the same in log statement.

2022-04-15 05:54 UTC, ParthaI reviewed
@karanpopat Make changes whenever required. Thanks!

2022-04-15 07:47 UTC, ParthaI approved these changes
LGTM

2022-04-15 12:19 UTC, cbruno10 requested changes
@karanpopat Please see comments, thanks!

2022-04-15 12:19 UTC, cbruno10 commented on docs/tables/digitalocean_database.md
> +### Get database firewall trusted sources
There should be a newline above this line (please see other examples above)

2022-04-15 12:19 UTC, cbruno10 commented on docs/tables/digitalocean_database.md
> +  firewall ->> 'type' as "Firewall Source",
Would it also be good to include the database name as a column? Else I imagine it may be difficult to tell which rules belong to which database

2022-04-18 11:48 UTC, cbruno10 approved these changes

2022-04-18 11:56 UTC, merged